config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  #resources :gamescores
  resources :users
  #resources :gameresults

  root 'static_pages#home'
  get 'sign_up' ,to:'users#new'
  get '/login',to:'sessions#new'
  post '/login',to:'sessions#create'
  delete '/logout',to:'sessions#destroy'
  get '/list',to:'static_pages#list'
  get '/ranking',to:'static_pages#ranking'
  get '/gameresults' ,to:'gameresults#new'
  post '/gameresults' ,to:'gameresults#create'
  delete '/gameresults' ,to:'gameresults#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gamedetail.rb
class Gamedetail < ApplicationRecord
  has_many :gameresults
end

app/models/gameresult.rb
class Gameresult < ApplicationRecord
  include ActiveModel::Model
  belongs_to :user
  belongs_to :gamedetail
  validates :score ,presence: true

  #formで使用するため、attr_accessorを定義
  attr_accessor :difficulty, :character

end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name,  presence: true,length: { maximum: 50 }
  validates :email, presence: true,length: { maximum: 255 }
  has_secure_password
#  validates :password ,presence: true,length: {minimum: 6}
  has_many :gameresults ,dependent: :delete_all



#  def authenticated?(remember_token)
#    return false if remember_digest.nil?
#    BCrypt::Password.new(remember_digest).is_password?(remember_token)
#  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/gameresults_controller.rb
class GameresultsController < ApplicationController
#before_action :gamescore_params,  only: :create


  def show
  end

  def new
    @game_title = params[:title]
    #@current_user=User.find_by(params[:id])
    @gameresult = Gameresult.new difficulty:"" ,character:""
    @difficulty = Gamedetail.where(gamename: @game_title).
    group("difficulty").order(:id).select("difficulty")
    @gamecharactor = Gamedetail.where(gamename: @game_title).
    group("character").order(:id).select("character")
  end

  def create
    #binding.pry
    #@current_user ||= User.find_by(id: session[:user_id])
    @current_user ||= User.new
    @gamedetail_id = Gamedetail.find_by(gamename: params[:gameresult][:name],difficulty: params[:gameresult][:difficulty],character: params[:gameresult][:character]).id
    @gamescoretest = Gameresult.new
    @gameresult = Gameresult.new
    @gameresult.user_id = session[:user_id]
    @gameresult.attributes = {gamedetail_id: @gamedetail_id,score: params[:gameresult][:score],clear: params[:gameresult][:clear]}
    #@gameresult.user_id = session[:user_id]
    if @gameresult.save
      flash[:success] = "スコア登録が完了しました!"
      render '/static_pages/list'
    else
      flash[:danger] = "スコア登録が失敗しました。半角数字で入力して下さい。"
      render '/static_pages/list'
    end
  end

  def destroy
    score_id = params[:score_id]
    if Gameresult.find_by_sql(['Delete from gameresults where id = ?',score_id])
      flash[:success]="chinko"
    else
      flash[:false]="unko"
    end
    redirect_to current_user
  end

  def update
  end

  def edit
  end

  private
  def gamescore_params
    params.require(:gameresult).permit(:gamedetail_id,:score,:clear)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
     if user && user.authenticate(params[:session][:password])
       log_in user
       redirect_to user
     else
      flash.now[:denger]= '無効な値です。メールアドレスまたはパスワードが誤っています。'
      render "new"
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def destroy
    log_out
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if logged_in?
      redirect_to current_user
    end
  end

  def list
  end

  def ranking
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_action :correct_user

  # GET /users
  # GET /users.json
  def index
    @users = User.paginate(page: params[:page])
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user=User.find(params[:id])
    @scorelist=Gameresult.where(user_id: @user.id)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    #binding.pry
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "登録が完了しました。"
      redirect_to @user
    else

    end

  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user = User.find(params[:id])
    if @user.update_columns(name: params[:user][:name],
      email: params[:user][:email],
      comment: params[:user][:comment])
      flash[:success] = "更新が完了しました。"
      redirect_to @user
    else
      render 'edit'
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name,:email,:password,:password_confirmation)
    end

    def user_profile
      params.require(:user).permit(:name,:email,:comment)
    end

    def correct_user
      @user = User.find(params[:id])
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
  def convert_to_japantime(time)
  t=time.in_time_zone('Tokyo')
  t.strftime("%Y-%m-%d　%H:%M　")
  end
end

app/helpers/gameresults_helper.rb
module GameresultsHelper
end

app/helpers/gamescore_helper.rb
module GamescoreHelper
end

app/helpers/registers_helper.rb
module RegistersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id]= user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def logged_in?
    !current_user.nil?
  end
  

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_controller_helper.rb
module UsersControllerHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { size: 50 })
   gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
   size = options[:size]
   gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
   image_tag(gravatar_url, alt: user.name, class: "gravatar")
 end

end

app/views/gameresults/new.html.erb
<%provide(:title,"スコア登録")%>

<h1><%= @game_title %> スコア登録</h1>

  <%= form_for(@gameresult) do |g|%>
  <%= g.hidden_field :name ,value: @game_title%>
  <%= g.label :difficulty,"難易度" %>
  <%= g.select :difficulty,@difficulty.all.map{|o| [o.difficulty]},class:"form-control"%>
  <%= g.label :character,"使用キャラクター" %>
  <%= g.select :character,@gamecharactor.all.map{|o| [o.character]},class:"form-control"%>
  <%= g.label :score,"スコア" %>
  <%= g.text_field :score%>
  <%= g.label :clear,"クリア有無" %>
  <%= g.select :clear,[["未クリア","未クリア"],["クリア","クリア"]],class:"form-control" %>
  <%= g.submit "スコア登録", class: "btn btn-primary" %>
  <%# binding.pry%>

<%end%>


<%= link_to 'Back', list_path %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to "お問合せ:sho shimohata","https://www.facebook.com/sho.shimohata"%>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "東方スコアボード", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "ホーム",   root_path %></li>
        <li><%= link_to "更新履歴",   '#' %></li>
        <%if logged_in? %>
         <li><%=link_to "ユーザ一覧",users_path%></li>
         <li class="dropdown">
           <a href="#" class="dropdown-toggle" data-toggle="dropdown">
             スコア<b class="caret" ></b>
           </a>
           <ul class="dropdown-menu">
             <li><%= link_to "スコア登録", list_path %></li>
             <li><%= link_to "ランキング", ranking_path %></li>
           </ul>
        </li>
        <li>
          <%= link_to "ログアウト", logout_path, method: :delete %>
        </li>

        <%else%>
          <li><%= link_to "ログイン", login_path %></li>
        <%end%>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>東方スコアボード</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all','data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application','data-turbolinks-track': 'reload' %>
        <!--[if lt IE 9]>
          <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
          </script>
        <![endif]-->
  </head>

  <body>
      <%=render 'layouts/header'%>

      <div class="container">
        <%flash.each do |message_type,message|%>
          <div class="alert alert-<%=message_type%>"><%=message%></div>
        <%end%>
        <%= yield %>
        <%=render 'layouts/footer'%>
        <%= debug(params) if Rails.env.development? %>
      </div>
  </body>
</html>

app/views/shared/_score_info.html.erb
<table class="table table-hover">
  <caption>最新登録スコア一覧</caption>
  <thead>
    <tr>
      <th>作品名</th>
      <th>難易度</th>
      <th>キャラクター</th>
      <th>スコア</th>
      <th>クリア可否</th>
      <th>登録日時</th>
    </tr>
  </thead>
  <tbody>
  <% @scorelist.each do |score|%>
  <tr>
    <th><%=score.gamedetail.gamename%></th>
    <th><%=score.gamedetail.difficulty%></th>
    <th><%=score.gamedetail.character%></th>
    <th><%=score.score%></th>
    <th><%=score.clear%></th>
    <th><%=convert_to_japantime(score.updated_at)%></th>
    <th><%=link_to "削除",gameresults_path(score_id: score.id),method: :delete,
            data:{confirm:"本当に削除しますか？"},class: "btn btn-xs btn-primary"%></th>
  <%end%>
  </tbody>
</table>

app/views/shared/_user_info.html.erb
<h1>
  <p>プロフィール</p>
  <%= gravatar_for @user%>
  <p>ユーザーネーム：<%= @user.name%></p>
  <%if current_user == @user%>
    <p>メールアドレス：<%= @user.email%></p>
  <%end%>
  <p>コメント</p>
  <%= @user.comment%>
  <%if current_user == @user%>
    <p class="text-right"><%= link_to '編集', edit_user_path(@user) ,class: "btn btn-xs btn-primary"%></p>
  <%end%>
</h1>

app/views/static_pages/home.html.erb
<div class= "text-center">
<h1>東方projectスコアボード</h1>
<h2>東方projectシリーズの<br>スコアやクリア履歴を管理するサイトですよ</h2>

<%=link_to "新規登録","sign_up",class: "btn btn-lg btn-primary"%>

</div>

app/views/static_pages/list.html.erb
<table class="table table-hover">

<thead>
  <tr>
    <th>発売年度</th>
    <th>作品名</th>
  </tr>
</thead>

<tbody>
  <tr>
    <th>2002年8月</th>
    <th><%=link_to "東方紅魔郷", gameresults_path(title: "東方紅魔郷") %></th>

  </tr>
  <tr>
    <th>2003年8月</th>
    <th><%=link_to "東方妖々夢" ,gameresults_path(title: "東方妖々夢")%></th>
  </tr>
  <tr>
    <th>2004年8月</th>
    <th><%=link_to "東方永夜抄" ,gameresults_path(title: "東方永夜抄")%></th>
  </tr>
  <tr>
    <th>2007年8月</th>
    <th><%=link_to "東方風神録" ,gameresults_path(title: "東方風神録")%></th>
  </tr>
  <tr>
    <th>2008年8月</th>
    <th><%=link_to "東方地霊殿" ,gameresults_path(title: "東方地霊殿")%></th>
  </tr>
  <tr>
    <th>2009年8月</th>
    <th><%=link_to "東方星蓮船" ,gameresults_path(title: "東方星蓮船")%></th>
  </tr>
  <tr>
    <th>2011年8月</th>
    <th><%=link_to "東方神霊廟" ,gameresults_path(title: "東方神霊廟")%></th>
  </tr>
  <tr>
    <th>2013年8月</th>
    <th><%=link_to "東方輝針城" ,gameresults_path(title: "東方輝針城")%></th>
  </tr>
  <tr>
    <th>2015年8月</th>
    <th><%=link_to "東方紺珠伝" ,gameresults_path(title: "東方紺珠伝")%></th>
  </tr>
  <tr>
    <th>2017年8月</th>
    <th><%=link_to "東方天空璋" ,gameresults_path(title: "東方天空璋")%></th>
  </tr>
</tbody>

</table>

app/views/static_pages/ranking.html.erb
<table class="table table-hover">
<h1>ランキング</h1>
<thead>
  <tr>
    <th>発売年度</th>
    <th>作品名</th>
  </tr>
</thead>

<tbody>
  <tr>
    <th>2002年8月</th>
    <th><%=link_to "東方紅魔郷", gameresults_path(title: "東方紅魔郷") %></th>

  </tr>
  <tr>
    <th>2003年8月</th>
    <th><%=link_to "東方妖々夢" ,gameresults_path(title: "東方妖々夢")%></th>
  </tr>
  <tr>
    <th>2004年8月</th>
    <th><%=link_to "東方永夜抄" ,gameresults_path(title: "東方永夜抄")%></th>
  </tr>
  <tr>
    <th>2007年8月</th>
    <th><%=link_to "東方風神録" ,gameresults_path(title: "東方風神録")%></th>
  </tr>
  <tr>
    <th>2008年8月</th>
    <th><%=link_to "東方地霊殿" ,gameresults_path(title: "東方地霊殿")%></th>
  </tr>
  <tr>
    <th>2009年8月</th>
    <th><%=link_to "東方星蓮船" ,gameresults_path(title: "東方星蓮船")%></th>
  </tr>
  <tr>
    <th>2011年8月</th>
    <th><%=link_to "東方神霊廟" ,gameresults_path(title: "東方神霊廟")%></th>
  </tr>
  <tr>
    <th>2013年8月</th>
    <th><%=link_to "東方輝針城" ,gameresults_path(title: "東方輝針城")%></th>
  </tr>
  <tr>
    <th>2015年8月</th>
    <th><%=link_to "東方紺珠伝" ,gameresults_path(title: "東方紺珠伝")%></th>
  </tr>
  <tr>
    <th>2017年8月</th>
    <th><%=link_to "東方天空璋" ,gameresults_path(title: "東方天空璋")%></th>
  </tr>
</tbody>

</table>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%provide(:title,"ユーザ編集")%>
<h1>ユーザー編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="gravatar_edit">
        <%= gravatar_for @user %>
        <br><br><br>
        <a href="http://gravatar.com/emails" target="_blank">プロフィール画像変更</a>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name,"名前" %>
      <%= f.text_field :name,value:@user.name, class: 'form-control' %>

      <%= f.label :email,"メールアドレス" %>
      <%= f.email_field :email,value:@user.email, class: 'form-control' %>

      <%= f.label :comment,"コメント"%>
      <%= f.text_field :comment,value:@user.comment, class: 'form-control' %>

      <%= f.submit "保存", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

<%= link_to '戻る', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>ユーザ一覧</h1>

<%= will_paginate%>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <ul class = "uses">
    <% @users.each do |user| %>
      <tr>
        <td><%= gravatar_for user%></td>
        <td><%= user.name%></td>
        <td><%= link_to 'スコア閲覧', user %></td>
        <%if current_user.admin?%>
        <td><%= link_to '削除', user, method: :delete, data: { confirm: '本当に削除しますか？' } %></td>
        <%end%>
      </tr>
    </ul>
    <% end %>
  </tbody>
</table>

<%= will_paginate%>

<br>

app/views/users/new.html.erb
<%provide(:title,"新規登録")%>

<h1>新規登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages'%>
      <%= f.label :name,"名前" %>
      <%= f.text_field :name%>

      <%= f.label :email,"メールアドレス" %>
      <%= f.email_field :email%>

      <%= f.label :password,"パスワード" %>
      <%= f.password_field :password%>

      <%= f.label :password_confirmation, "パスワード再入力" %>
      <%= f.password_field :password_confirmation%>

      <%= f.submit "アカウント登録", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%provide(:title,@user.name)%>

<div class = "row">
  <aside class="span4">
    <section class="user_info">
      <%= render 'shared/user_info'%>
    </section>
  </dev>
  <div class="span8">
    <section class="score_info">
      <%= render 'shared/score_info'%>
    </section>
  </div>